services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "repsesystem"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: repse
    ports:
      - "1433:1433"
    networks:
        - backend

networks:
    backend:
        driver: bridge